apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend0
  labels:
    global: tp
    type: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend0
  template:
    metadata:
      labels:
        app: backend0
    spec:
      containers:
      - name: backend0
        image: backend0:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend0-svc
  labels:
    global: tp
    type: back
spec:
  selector:
    app: backend0
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend1
  labels:
    global: tp
    type: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend1
  template:
    metadata:
      labels:
        app: backend1
    spec:
      containers:
      - name: backend1
        image: backend1:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend1-svc
  labels:
    global: tp
    type: back
spec:
  selector:
    app: backend1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend2
  template:
    metadata:
      labels:
        app: backend2
    spec:
      containers:
      - name: backend2
        image: backend2:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-svc
  labels:
    global: tp
    type: back
spec:
  selector:
    app: backend2
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
