apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    global: tp
    type: front
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort