apiVersion: apps/v1

kind: Deployment

metadata:
  name: frontend
  labels:
    global: tp
    type: front

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

      annotations:
        kubernetes.io/change-cause: "Updated to latest frontend version"

    spec:
      containers:
      - name: frontend
        image: frontend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND0_URL
          value: "http://backend-svc0:5000"
        - name: BACKEND1_URL
          value: "http://backend-svc1:5000"
        - name: BACKEND2_URL
          value: "http://backend-svc2:5000"